export const REQUEST_API_DATA = "REQUEST_API_DATA";
export const RECEIVE_API_DATA = "RECEIVE_API_DATA";
export const RECEIVE_API_DATA_SUCCESS = "RECEIVE_API_DATA_SUCCESS";
export const RECEIVE_API_DATA_ERROR = "RECEIVE_API_DATA_ERROR";
export const REQUEST_API_DATA_URL = "REQUEST_API_DATA_URL";
export const RECEIVE_API_DATA_URL = "RECEIVE_API_DATA_URL";
export const RECEIVE_API_DATA_URL_SUCCESS = "RECEIVE_API_DATA_URL_SUCCESS";
export const RECEIVE_API_DATA_URL_ERROR = "RECEIVE_API_DATA_URL_ERROR";