export const REQUEST_API_DATA = "REQUEST_API_DATA";
export const RECEIVE_API_DATA = "RECEIVE_API_DATA";
export const REQUEST_API_DATA_URL = "REQUEST_API_DATA_URL";
export const RECEIVE_API_DATA_URL = "RECEIVE_API_DATA_URL";